# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open Infrastructure Orbit
logo: /images/rc3-oio-a_f-light.svg
logo-dark: /images/rc3-oio-a_f-dark.svg
email: 35c3-orga@freifunk.space
description: >- # this means to ignore newlines until "baseurl:"
  Der Open Infrastructure Orbit bietet allen Vereinigungen rund um das Thema “Offene Infrastruktur” die Möglichkeit, ihre Projekte und Konzepte zu präsentieren und sich miteinander auszutauschen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oio.social" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: openinfraorbit
minimal_mistakes_skin: "neon"
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/openinfraorbit"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/openinfrastructureorbit"
    - label: "IRC"
      icon: "far fa-comment-dots"
      url: "https://webirc.hackint.org/#irc://irc.hackint.org/#oio-stage"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.14.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _news
  - scope:
      path: ""
      type: news
    values:
      layout: single


lang: de
languages: ["de", "en"]
collections:
  assemblies:
    output: true
    permalink: /:collection/:path/
  news:
    output: false
    permalink: /:collection/:path/
include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: [vendor]
